name: Deploy to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: List files in current directory
        run: ls -R

      - name: Deploy with Ansible
        run: |
          cd my-website/ansible
          ansible-playbook -i inventory.ini deploy.yml
