name: Deploy to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH Agent
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          # Add GitHub's SSH key to known hosts to avoid issues with untrusted hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Debug - Check Current Directory
        run: pwd

      - name: Debug - List All Files
        run: ls -R

      - name: Deploy with Ansible
        env:
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          cd ansible  # Change into the ansible directory
          ansible-playbook -i inventory.ini deploy.yml -u ${{ secrets.ANSIBLE_USER }}
